language: java
jdk:
  - openjdk11
script:
  - mvn clean package
deploy:
    provider: heroku
    api_key:
      secure: M+MJWNEeolhUUnux8AJ3Afl2z/8QGxYE99nkODfg+EV6DtkyRf9OnzK+woH9ucdAKhVFKotxPSZQ77CbKY59G///0vqvrr8hIqDP6MeLQUPQuYZjVpaDKLF/ojztkukwNbE+9Ei7dapmFcC1FSnydMAAkYrFc3wR+0kgdJgnFWguoj6hGU0ie+T6z589a+vGWQeLIr41nX8+o8MQRfZF/bIZKYnFysVY2Umwsy3PjDY0QUzFEd7KyqN7YCV/hN85wHzM+hLGivhHG4cuCCyT+oiYT5ZmG2tIP+JVt7+vTAUtWoPpTMbEubUwIdeAjfV6forzEQ8e5NfpE3K1CDXvCiXWaNm6Q8QfdTbXREw/T7znce4dmP0tGd8PBp0bwRol5QpAoRbSpTt4Vy7+UKtpo853Wqks2LxCCwRaXmCKgYqbvcLgmhZ9ApQruIVDoswsASujbjRyPFyIGujTSvw5FSvycMW8GfHypmsf6YLSaiUwKmLiJmisjzwHssxKv/DnPf7qZXJR8JYAAitxawrVYa8oZ+fMu1gvQi8pIv7NlzUD1xsSuP2vKvfiQ2FSt+QsRzZi2xZKatGQ0XRwoTNdreMXt9Tzq+6bELObI4vaM+MNMh92cc2r9eOoISMQmd45on3NIYZ4BqaR3+SDKNHZsUdNBxhfVg2J6o0WqfljXpg=
    app: wsc-rating-service
    on:
      repo: lilo2k/wsc_rating
      branch: master
